name: Java CI with Gradle

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Start SUT
        run: java -jar artifacts/app-ibank.jar -P:profile=test &

      - name: Wait for app to start
        run: |
          for i in {1..30}; do
            if curl -f -s http://localhost:9999 > /dev/null; then
              echo "App is ready!"
              break
            fi
            echo "Waiting for app to start... ($i/30)"
            sleep 2
          done

      - name: Clean browser processes and temp files
        run: |
          pkill -f chrome || true
          pkill -f chromedriver || true
          rm -rf /tmp/.com.google.Chrome.* || true
          rm -rf /tmp/chrome-profile* || true
          sleep 3

      - name: Test with Gradle
        run: ./gradlew test --info