name: Java CI with Gradle

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Chrome for Selenide
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Start application in test mode
        run: |
          java -jar artifacts/app-ibank.jar -P:profile=test &
          echo "Waiting for app to start..."
          sleep 15
          echo "Application should be running now"

      - name: Test with Gradle
        run: ./gradlew test --info -Dselenide.headless=true

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            build/reports/tests/test/
            build/test-results/test/