name: Java CI with Gradle

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Firefox for Selenide
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Start SUT
        run: java -jar artifacts/app-ibank.jar -P:profile=test &

      - name: Wait for app to start
        run: |
          for i in {1..30}; do
            if curl -f -s http://localhost:9999 > /dev/null; then
              echo "App is ready!"
              break
            fi
            echo "Waiting for app to start... ($i/30)"
            sleep 2
          done

      - name: Test with Gradle
        run: ./gradlew test --info