name: Java CI with Gradle

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Start SUT
        run: java -jar artifacts/app-ibank.jar -P:profile=test &

      - name: Wait for app to start
        run: |
          timeout 30s bash -c '
            while ! curl -f http://localhost:9999; do
              echo "Waiting for app to start..."
              sleep 3
            done
          ' || exit 1

      - name: Clean up browser processes
        run: |
          pkill -f chrome || true
          pkill -f chromedriver || true
          sleep 2

      - name: Test with Gradle
        run: ./gradlew test --info -Dselenide.headless=true