name: Java Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Start application in test mode
        run: java -jar artifacts/app-ibank.jar -P:profile=test &


      - name: Run tests with detailed info
        run: ./gradlew test --info